name: pure_pitch
description: "PurePitch is a tool that can test a person's vocal pitch. Supports Android, iOS, Windows, MacOS, and Linux."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_lib_pure_pitch:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  record: ^6.1.2
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  freezed_annotation: ^3.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  file_picker: ^8.1.7
  go_router: ^17.0.1
  go_router_builder: ^4.1.3
  path_provider: ^2.1.5
  talker_flutter: ^5.1.9
  talker_riverpod_logger: ^5.1.9
  clock: ^1.1.2
  collection: ^1.19.1
  path: ^1.9.1
  drift: ^2.30.1
  sqlite3_flutter_libs: ^0.5.41
  just_audio: ^0.10.5
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.5
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  freezed: ^3.2.3
  intl_utils: ^2.8.13
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  riverpod: ^3.1.0
  mocktail: ^1.0.4
  fake_async: ^1.3.3
  drift_dev: ^2.30.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
